name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Pandapip1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: A clear and concise description of what the bug is.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you running?
      options:
        - v1.4.0
        - v1.3.3
        - v1.3.2
        - v1.3.1
        - v1.3.0
        - v1.2.2
        - v1.2.1
        - v1.2.0
        - v1.1.1
        - v1.1.0
        - v1.0.1
        - v1.0.0
    validations:
      required: true
  - type: dropdown
    id: oses
    attributes:
      label: What OSes are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac OS X
        - Debian-based Linux (Debian, Ubuntu, etc...)
        - Red Hat-based Linux (RHEL, Fedora, etc...)
        - Chrome OS
        - Android
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Google Chrome
        - Chromium
        - Ungoogled Chromium
        - Brave
        - Other
  - type: input
    id: browversion
    attributes:
      label: What browser versions are you seeing the problem on?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: existing
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
