name: Missing Accent
description: Report a missing accent in a language that has already been added
title: "[Missing Accent]: "
labels: ["bug", "language"]
assignees:
  - Pandapip1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: input
    id: lang
    attributes:
      label: Language Code
      description: Language Code for the language missing the accent
      placeholder: e.g. fr
  - type: input
    id: accents
    attributes:
      label: Missing Accents
      description: The missing accent(s) (w/o any seperation in the case of multiple missing accents)
      placeholder: e.g. éê
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
