name: Build CRX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: ${ env.GITHUB_WORKSPACE }
          zipFilePath: 'build/extension.zip'

      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/extension.crx'
          privateKey: ${{ secrets.RSA_PRIV }}
      
      - uses: actions/upload-artifact@v2
        with:
          name: extension
          path: build/extension.crx
