name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildcrx:
    name: "Build CRX"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: extension
      
      - uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'extension'
          zipFilePath: 'build/extension.zip'

      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/extension.crx'
          privateKey: ${{ secrets.RSA_PRIV }}
  buildzip:
    name: "Build Unpacked ZIP"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: extension
      
      - name: "Remove unnecesary files"
        run: |
          rm -f extension/html/popup.html
          rm -f extension/css/popup.css
          rm -f extension/js/popup.js
          rm -f extension/CNAME
          rm -f extension/README.md
          rm -rf extension/vendor
          rm -rf extension/config
          rm -rf extension/.github
      
      - uses: actions/upload-artifact@v2
        with:
          name: extension
          path: extension
