name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '22 7 * * 0'

jobs:
  codeql:
    name: CodeQL Security Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
  buildzip:
    name: Build Unpacked ZIP
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: extension
      
      - name: Remove unnecesary files
        run: |
          rm -f extension/html/popup.html
          rm -f extension/css/popup.css
          rm -f extension/js/popup.js
          rm -f extension/CNAME
          rm -f extension/README.md
          rm -rf extension/vendor
          rm -rf extension/config

          rm -f extension/SECURITY.md
          rm -f CODE_OF_CONDUCT.md
          rm -f CONTRIBUTING.md
          rm -f extension/LICENCE
          rm -f extension/.gitpod.yml
          rm -rf extension/.github
      
      - name: Build ZIP for Validation
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: extension
          zipFilePath: build/extension.zip

      - name: Validate Extension
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: build/extension.zip
          crxFilePath: build/extension.crx
          privateKey: ${{ secrets.RSA_PRIV }}
      
      - name: Upload Extension
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: extension
  buildpages:
    name: Build GitHub Pages
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    needs: codeql
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main
      
      - name: Remove unnecesary files
        run: |
          rm -f html/extension_settings.html
          rm -f manifest.json
          rm -rf _locales
          rm -f js/inject.js
          rm -f js/inject_gdoc.js
          rm -f js/background.js

          rm -f SECURITY.md
          rm -f LICENCE
          rm -f .gitpod.yml
          rm -rf .github
     
      - name: Minify JS and CSS
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
      
      - name: Deploy to GH Pages
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Commit Updated Files
          branch: gh-pages
          push_options: --force
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
